apiVersion: v1
kind: Service

metadata:
  name: order-service
  namespace: ecommerce

spec:
  selector:
    app: order-service

  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30869

  type: NodePort # used for external (outside kubernetes)
  # type: ClusterIP #  used when there is a internal communication between microservices 